version: "3"

services:
  db:
    container_name: server-curso
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    volumes:
      - mysql-curso:/var/lib/mysql
    networks:
      - curso-net

  server:
    container_name: server-nodejs
    image: cursonodejs
    build: .
    ports:
      - "80:80"
    depends_on:
      - "db"
    restart: always
    networks:
      - curso-net

volumes:
  mysql-curso:

networks:
  curso-net:
