version: "3"

services:
  db:
    container_name: server-curso
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    volumes:
      - mysql-curso:/var/lib/mysql

volumes:
  mysql-curso:
